#!/usr/bin/env bash

url="$1"

if [[ "$url" == *"youtube.com"* ]] && [[ "$url" == *"/playlist"* ]]; then
    flags=""
else
    flags="--playlist-reverse"
fi

yt-dlp --output-na-placeholder '' $flags -f 'bestvideo[vcodec!*=av01]+bestaudio/best' --output '%(playlist_autonumber,uploader)s - %(title)s.%(ext)s' "$url"
