#!/usr/bin/env bash

max_res="res:480" # 480p max resolution
target_size_mb=7 # 8MB target size, but 1MB headroom
target_audio_bitrate=128 # 128kbps target audio bitrate
audio_only=0

# Thanks to 'Chris Pearson' (Aug 15, 2020) for getopts example
# https://stackoverflow.com/a/40190976

while [ $OPTIND -le "$#" ]
do
    if getopts na option
    then
        case $option
        in
            n) max_res="res:720" # 720p max resolution
	       target_size_mb=38  # 40MB target size, but 2MB headroom
	       target_audio_bitrate=320 # 320kbps target audio bitrate
	       ;;
            a) audio_only=1
	       ;;
        esac
    else
        script_args+=("${!OPTIND}")
        ((OPTIND++))
    fi
done

# Thanks to 'tobek' for duration and bitrate calculation examples
# https://unix.stackexchange.com/a/598360

duration=$(yt-dlp --no-warnings --get-duration ${script_args[@]} | awk -F: '{ print ($1 * 60) + $2 }')
target_size=$(($target_size_mb * 1000 * 1000 * 8)) # target size in bits
duration_round_up=$((${duration%.*} + 1))

total_bitrate=$(($target_size / $duration_round_up))
audio_bitrate=$(($target_audio_bitrate * 1000))
video_bitrate=$(($total_bitrate - $audio_bitrate))

# If calculated video bitrate is negative, reduce audio bitrate
if [[ ! $video_bitrate -gt 0 ]]
then
   audio_bitrate=$((96 * 1000))
   video_bitrate=$(($total_bitrate - $audio_bitrate))
fi

postprocessor_args_str="VideoConvertor:-b:v ${video_bitrate} -maxrate:v ${video_bitrate} -bufsize:v $((${target_size} / 20)) -b:a ${audio_bitrate}"
yt_dlp_params="--recode-video mp4 -S ${max_res}"
alt_params="--format bestaudio --extract-audio --audio-format mp3 --audio-quality $(($total_bitrate / 1000))k"

if [ "$audio_only" = "1" ]
then 
   postprocessor_args_str="ffmpeg:"
   yt_dlp_params=$alt_params
fi

yt-dlp -v ${yt_dlp_params} --postprocessor-args "${postprocessor_args_str}" --output '%(title)s.%(ext)s' ${script_args[@]}
